// Code generated by protoc-gen-go. DO NOT EDIT.
// source: party.proto

package partyProto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nil) Reset()         { *m = Nil{} }
func (m *Nil) String() string { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()    {}
func (*Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{0}
}

func (m *Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nil.Unmarshal(m, b)
}
func (m *Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nil.Marshal(b, m, deterministic)
}
func (m *Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nil.Merge(m, src)
}
func (m *Nil) XXX_Size() int {
	return xxx_messageInfo_Nil.Size(m)
}
func (m *Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Nil proto.InternalMessageInfo

type ExitMetaPartyReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PartyId              string   `protobuf:"bytes,2,opt,name=partyId,proto3" json:"partyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitMetaPartyReq) Reset()         { *m = ExitMetaPartyReq{} }
func (m *ExitMetaPartyReq) String() string { return proto.CompactTextString(m) }
func (*ExitMetaPartyReq) ProtoMessage()    {}
func (*ExitMetaPartyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{1}
}

func (m *ExitMetaPartyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitMetaPartyReq.Unmarshal(m, b)
}
func (m *ExitMetaPartyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitMetaPartyReq.Marshal(b, m, deterministic)
}
func (m *ExitMetaPartyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitMetaPartyReq.Merge(m, src)
}
func (m *ExitMetaPartyReq) XXX_Size() int {
	return xxx_messageInfo_ExitMetaPartyReq.Size(m)
}
func (m *ExitMetaPartyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitMetaPartyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExitMetaPartyReq proto.InternalMessageInfo

func (m *ExitMetaPartyReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ExitMetaPartyReq) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

type JoinMetaPartyReq struct {
	PartyId     string `protobuf:"bytes,1,opt,name=partyId,proto3" json:"partyId,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	AppVersion  string `protobuf:"bytes,3,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	AppLanguage string `protobuf:"bytes,4,opt,name=appLanguage,proto3" json:"appLanguage,omitempty"`
	//#JoinMetaPartyReq.followUid.desc: 跟随的用户ID#
	FollowUid            string   `protobuf:"bytes,5,opt,name=followUid,proto3" json:"followUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinMetaPartyReq) Reset()         { *m = JoinMetaPartyReq{} }
func (m *JoinMetaPartyReq) String() string { return proto.CompactTextString(m) }
func (*JoinMetaPartyReq) ProtoMessage()    {}
func (*JoinMetaPartyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{2}
}

func (m *JoinMetaPartyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinMetaPartyReq.Unmarshal(m, b)
}
func (m *JoinMetaPartyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinMetaPartyReq.Marshal(b, m, deterministic)
}
func (m *JoinMetaPartyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinMetaPartyReq.Merge(m, src)
}
func (m *JoinMetaPartyReq) XXX_Size() int {
	return xxx_messageInfo_JoinMetaPartyReq.Size(m)
}
func (m *JoinMetaPartyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinMetaPartyReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinMetaPartyReq proto.InternalMessageInfo

func (m *JoinMetaPartyReq) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

func (m *JoinMetaPartyReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *JoinMetaPartyReq) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *JoinMetaPartyReq) GetAppLanguage() string {
	if m != nil {
		return m.AppLanguage
	}
	return ""
}

func (m *JoinMetaPartyReq) GetFollowUid() string {
	if m != nil {
		return m.FollowUid
	}
	return ""
}

type MetaParty struct {
	PartyId string `protobuf:"bytes,1,opt,name=partyId,proto3" json:"partyId,omitempty"`
	//#MetaParty.type.desc: 类型#
	Type int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	//#MetaParty.name.desc: 派对名称#
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	//#MetaParty.teamId.desc: 群聊ID#
	TeamId string `protobuf:"bytes,4,opt,name=teamId,proto3" json:"teamId,omitempty"`
	//#MetaParty.onlineMembers.desc: 在线成员#
	OnlineMembers []*MetaPartyUser `protobuf:"bytes,5,rep,name=onlineMembers,proto3" json:"onlineMembers,omitempty"`
	//#MetaParty.maxCount.desc: 最大成员数#
	MaxCount int32 `protobuf:"varint,6,opt,name=maxCount,proto3" json:"maxCount,omitempty"`
	//#MetaParty.family.desc: 家族信息#
	Family *FamilyData `protobuf:"bytes,7,opt,name=family,proto3" json:"family,omitempty"`
	//#MetaParty.sceneId.desc: 场景ID#
	SceneId string `protobuf:"bytes,8,opt,name=sceneId,proto3" json:"sceneId,omitempty"`
	//#MetaParty.convId.desc: 会话ID#
	ConvId string `protobuf:"bytes,9,opt,name=convId,proto3" json:"convId,omitempty"`
	//#MetaParty.rtcId.desc: RtcID#
	RtcId                string   `protobuf:"bytes,10,opt,name=rtcId,proto3" json:"rtcId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaParty) Reset()         { *m = MetaParty{} }
func (m *MetaParty) String() string { return proto.CompactTextString(m) }
func (*MetaParty) ProtoMessage()    {}
func (*MetaParty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{3}
}

func (m *MetaParty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaParty.Unmarshal(m, b)
}
func (m *MetaParty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaParty.Marshal(b, m, deterministic)
}
func (m *MetaParty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaParty.Merge(m, src)
}
func (m *MetaParty) XXX_Size() int {
	return xxx_messageInfo_MetaParty.Size(m)
}
func (m *MetaParty) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaParty.DiscardUnknown(m)
}

var xxx_messageInfo_MetaParty proto.InternalMessageInfo

func (m *MetaParty) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

func (m *MetaParty) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MetaParty) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaParty) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *MetaParty) GetOnlineMembers() []*MetaPartyUser {
	if m != nil {
		return m.OnlineMembers
	}
	return nil
}

func (m *MetaParty) GetMaxCount() int32 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

func (m *MetaParty) GetFamily() *FamilyData {
	if m != nil {
		return m.Family
	}
	return nil
}

func (m *MetaParty) GetSceneId() string {
	if m != nil {
		return m.SceneId
	}
	return ""
}

func (m *MetaParty) GetConvId() string {
	if m != nil {
		return m.ConvId
	}
	return ""
}

func (m *MetaParty) GetRtcId() string {
	if m != nil {
		return m.RtcId
	}
	return ""
}

type MetaPartyUser struct {
	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AvatarUrl string `protobuf:"bytes,2,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	Sex       int32  `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Age       int32  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	//#MetaPartyUser.rls.desc: 关系：0-无；1-好友；……#
	Rls                  int32    `protobuf:"varint,5,opt,name=rls,proto3" json:"rls,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaPartyUser) Reset()         { *m = MetaPartyUser{} }
func (m *MetaPartyUser) String() string { return proto.CompactTextString(m) }
func (*MetaPartyUser) ProtoMessage()    {}
func (*MetaPartyUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{4}
}

func (m *MetaPartyUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaPartyUser.Unmarshal(m, b)
}
func (m *MetaPartyUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaPartyUser.Marshal(b, m, deterministic)
}
func (m *MetaPartyUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaPartyUser.Merge(m, src)
}
func (m *MetaPartyUser) XXX_Size() int {
	return xxx_messageInfo_MetaPartyUser.Size(m)
}
func (m *MetaPartyUser) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaPartyUser.DiscardUnknown(m)
}

var xxx_messageInfo_MetaPartyUser proto.InternalMessageInfo

func (m *MetaPartyUser) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MetaPartyUser) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *MetaPartyUser) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *MetaPartyUser) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *MetaPartyUser) GetRls() int32 {
	if m != nil {
		return m.Rls
	}
	return 0
}

func (m *MetaPartyUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FamilyData struct {
	// #FamilyData.familyId.desc:家族id#
	FamilyId string `protobuf:"bytes,1,opt,name=familyId,proto3" json:"familyId,omitempty"`
	// #FamilyData.name.desc:家族名#
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// #FamilyData.iconUrl.desc:家族icon#
	IconUrl string `protobuf:"bytes,3,opt,name=iconUrl,proto3" json:"iconUrl,omitempty"`
	// #FamilyData.founder.desc:家族创始人#
	Founder string `protobuf:"bytes,4,opt,name=founder,proto3" json:"founder,omitempty"`
	// #FamilyData.notice.desc:家族公告#
	Notice string `protobuf:"bytes,5,opt,name=notice,proto3" json:"notice,omitempty"`
	// #FamilyData.level.desc:家族等级#
	Level int32 `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	// #FamilyData.integral.desc:家族当前积分#
	Integral int64 `protobuf:"varint,7,opt,name=integral,proto3" json:"integral,omitempty"`
	// #FamilyData.relegationProgress.desc:保级进度#
	RelegationProgress string `protobuf:"bytes,8,opt,name=relegationProgress,proto3" json:"relegationProgress,omitempty"`
	// #FamilyData.nextLevelIntegral.desc:家族下个等级所需积分#
	NextLevelIntegral int64 `protobuf:"varint,9,opt,name=nextLevelIntegral,proto3" json:"nextLevelIntegral,omitempty"`
	// #FamilyData.status.desc:家族状态  0=待激活 1=生效中 2=已失效(需提示) 3=已解散#
	Status int32 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	// #FamilyData.role.desc:用户角色  0=游客 1=族长 2=副族长 3=普通家族成员#
	Role int32 `protobuf:"varint,11,opt,name=role,proto3" json:"role,omitempty"`
	// #FamilyData.membersCount.desc:成员数量#
	MembersCount int32 `protobuf:"varint,12,opt,name=membersCount,proto3" json:"membersCount,omitempty"`
	// #FamilyData.maxMembersCount.desc:最大成员数量#
	MaxMembersCount int32 `protobuf:"varint,13,opt,name=maxMembersCount,proto3" json:"maxMembersCount,omitempty"`
	// #FamilyData.createTime.desc:家族创建时间#
	CreateTime int32 `protobuf:"varint,14,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// #FamilyData.shareUrl.desc:家族分享链接#
	ShareUrl string `protobuf:"bytes,15,opt,name=shareUrl,proto3" json:"shareUrl,omitempty"`
	// #FamilyData.inviteUrl.desc:家族邀请链接#
	InviteUrl string `protobuf:"bytes,16,opt,name=inviteUrl,proto3" json:"inviteUrl,omitempty"`
	// #FamilyData.teamId.desc:家族群聊id#
	TeamId string `protobuf:"bytes,17,opt,name=teamId,proto3" json:"teamId,omitempty"`
	// #FamilyData.convId.desc:家族群聊会话id#
	ConvId               string   `protobuf:"bytes,18,opt,name=convId,proto3" json:"convId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FamilyData) Reset()         { *m = FamilyData{} }
func (m *FamilyData) String() string { return proto.CompactTextString(m) }
func (*FamilyData) ProtoMessage()    {}
func (*FamilyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{5}
}

func (m *FamilyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyData.Unmarshal(m, b)
}
func (m *FamilyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyData.Marshal(b, m, deterministic)
}
func (m *FamilyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyData.Merge(m, src)
}
func (m *FamilyData) XXX_Size() int {
	return xxx_messageInfo_FamilyData.Size(m)
}
func (m *FamilyData) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyData.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyData proto.InternalMessageInfo

func (m *FamilyData) GetFamilyId() string {
	if m != nil {
		return m.FamilyId
	}
	return ""
}

func (m *FamilyData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FamilyData) GetIconUrl() string {
	if m != nil {
		return m.IconUrl
	}
	return ""
}

func (m *FamilyData) GetFounder() string {
	if m != nil {
		return m.Founder
	}
	return ""
}

func (m *FamilyData) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *FamilyData) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *FamilyData) GetIntegral() int64 {
	if m != nil {
		return m.Integral
	}
	return 0
}

func (m *FamilyData) GetRelegationProgress() string {
	if m != nil {
		return m.RelegationProgress
	}
	return ""
}

func (m *FamilyData) GetNextLevelIntegral() int64 {
	if m != nil {
		return m.NextLevelIntegral
	}
	return 0
}

func (m *FamilyData) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FamilyData) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *FamilyData) GetMembersCount() int32 {
	if m != nil {
		return m.MembersCount
	}
	return 0
}

func (m *FamilyData) GetMaxMembersCount() int32 {
	if m != nil {
		return m.MaxMembersCount
	}
	return 0
}

func (m *FamilyData) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *FamilyData) GetShareUrl() string {
	if m != nil {
		return m.ShareUrl
	}
	return ""
}

func (m *FamilyData) GetInviteUrl() string {
	if m != nil {
		return m.InviteUrl
	}
	return ""
}

func (m *FamilyData) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *FamilyData) GetConvId() string {
	if m != nil {
		return m.ConvId
	}
	return ""
}

func init() {
	proto.RegisterType((*Nil)(nil), "partyProto.Nil")
	proto.RegisterType((*ExitMetaPartyReq)(nil), "partyProto.ExitMetaPartyReq")
	proto.RegisterType((*JoinMetaPartyReq)(nil), "partyProto.JoinMetaPartyReq")
	proto.RegisterType((*MetaParty)(nil), "partyProto.MetaParty")
	proto.RegisterType((*MetaPartyUser)(nil), "partyProto.MetaPartyUser")
	proto.RegisterType((*FamilyData)(nil), "partyProto.FamilyData")
}

func init() { proto.RegisterFile("party.proto", fileDescriptor_f8c47bfae09949f0) }

var fileDescriptor_f8c47bfae09949f0 = []byte{
	// 647 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x93, 0x3a, 0x6d, 0x26, 0x0d, 0x4d, 0x57, 0x50, 0x2d, 0x55, 0x85, 0x22, 0x9f, 0x72,
	0x40, 0x39, 0x94, 0x07, 0x00, 0x89, 0x52, 0xc9, 0xa8, 0x45, 0x95, 0xa1, 0xdc, 0xb7, 0xf1, 0x34,
	0xac, 0x64, 0xef, 0x9a, 0xf5, 0x26, 0xa4, 0x4f, 0xc1, 0x95, 0x03, 0x47, 0x9e, 0x82, 0xa7, 0x43,
	0xb3, 0xde, 0xf8, 0xa7, 0x14, 0x6e, 0xf3, 0x7d, 0x33, 0x1e, 0x7f, 0x3b, 0xdf, 0xec, 0xc2, 0xa8,
	0x10, 0xc6, 0xde, 0xcf, 0x0b, 0xa3, 0xad, 0x66, 0xe0, 0xc0, 0x35, 0xc5, 0x51, 0x08, 0xfd, 0x0f,
	0x32, 0x8b, 0xce, 0x61, 0xf2, 0x6e, 0x23, 0xed, 0x15, 0x5a, 0x71, 0x4d, 0xc9, 0x04, 0xbf, 0xb2,
	0x63, 0x18, 0xac, 0x4a, 0x34, 0x71, 0xca, 0x83, 0x69, 0x30, 0x1b, 0x26, 0x1e, 0x31, 0x0e, 0x7b,
	0xae, 0x41, 0x9c, 0xf2, 0x9e, 0x4b, 0x6c, 0x61, 0xf4, 0x2b, 0x80, 0xc9, 0x7b, 0x2d, 0x55, 0xa7,
	0x4d, 0xab, 0x3c, 0xe8, 0x94, 0xb7, 0x7e, 0xd0, 0xeb, 0xfc, 0xe0, 0x05, 0x80, 0x28, 0x8a, 0xcf,
	0x68, 0x4a, 0xa9, 0x15, 0xef, 0xbb, 0x5c, 0x8b, 0x61, 0x53, 0x18, 0x89, 0xa2, 0xb8, 0x14, 0x6a,
	0xb9, 0x12, 0x4b, 0xe4, 0xbb, 0xae, 0xa0, 0x4d, 0xb1, 0x53, 0x18, 0xde, 0xe9, 0x2c, 0xd3, 0xdf,
	0x6e, 0x64, 0xca, 0x43, 0x97, 0x6f, 0x88, 0xe8, 0x77, 0x0f, 0x86, 0xb5, 0xc4, 0xff, 0xe8, 0x63,
	0xb0, 0x6b, 0xef, 0x0b, 0x74, 0xea, 0xc2, 0xc4, 0xc5, 0xc4, 0x29, 0x91, 0xa3, 0x57, 0xe5, 0x62,
	0x3a, 0x87, 0x45, 0x91, 0xc7, 0xa9, 0x97, 0xe2, 0x11, 0x7b, 0x0d, 0x63, 0xad, 0x32, 0xa9, 0xf0,
	0x0a, 0xf3, 0x5b, 0x34, 0x25, 0x0f, 0xa7, 0xfd, 0xd9, 0xe8, 0xec, 0xf9, 0xbc, 0x99, 0xff, 0xbc,
	0xd6, 0x71, 0x53, 0xa2, 0x49, 0xba, 0xf5, 0xec, 0x04, 0xf6, 0x73, 0xb1, 0x79, 0xab, 0x57, 0xca,
	0xf2, 0x81, 0x13, 0x51, 0x63, 0x36, 0x87, 0xc1, 0x9d, 0xc8, 0x65, 0x76, 0xcf, 0xf7, 0xa6, 0xc1,
	0x6c, 0x74, 0x76, 0xdc, 0xee, 0x7a, 0xe1, 0x32, 0xe7, 0xc2, 0x8a, 0xc4, 0x57, 0xd1, 0x31, 0xcb,
	0x05, 0x2a, 0x8c, 0x53, 0xbe, 0x5f, 0x1d, 0xd3, 0x43, 0x92, 0xbf, 0xd0, 0x6a, 0x1d, 0xa7, 0x7c,
	0x58, 0xc9, 0xaf, 0x10, 0x7b, 0x0a, 0xa1, 0xb1, 0x8b, 0x38, 0xe5, 0xe0, 0xe8, 0x0a, 0x44, 0xdf,
	0x03, 0x18, 0x77, 0x44, 0xff, 0x73, 0x4f, 0x4e, 0x61, 0x28, 0xd6, 0xc2, 0x0a, 0x73, 0x63, 0x32,
	0xef, 0x70, 0x43, 0xb0, 0x09, 0xf4, 0x4b, 0xdc, 0xb8, 0x39, 0x86, 0x09, 0x85, 0xc4, 0x6c, 0xed,
	0x0c, 0x13, 0x0a, 0x89, 0x31, 0x59, 0xe9, 0x0c, 0x0c, 0x13, 0x0a, 0xeb, 0xf1, 0x0f, 0x9a, 0xf1,
	0x47, 0x3f, 0x77, 0x01, 0x9a, 0x03, 0xd3, 0xd0, 0xaa, 0x23, 0xd7, 0x82, 0x6a, 0x5c, 0x7f, 0xde,
	0x6b, 0xb9, 0xc7, 0x61, 0x4f, 0x2e, 0xb4, 0x22, 0x91, 0x95, 0xa9, 0x5b, 0x48, 0x99, 0x3b, 0xbd,
	0x52, 0x29, 0x1a, 0x6f, 0xec, 0x16, 0xd2, 0x91, 0x95, 0xb6, 0x72, 0x81, 0x7e, 0xb9, 0x3c, 0xa2,
	0x91, 0x65, 0xb8, 0xc6, 0xcc, 0xbb, 0x55, 0x01, 0x52, 0x24, 0x95, 0xc5, 0xa5, 0x11, 0x99, 0x33,
	0xab, 0x9f, 0xd4, 0x98, 0xcd, 0x81, 0x19, 0xcc, 0x70, 0x29, 0xac, 0xd4, 0xea, 0xda, 0xe8, 0xa5,
	0xc1, 0xb2, 0xf4, 0x0e, 0x3d, 0x92, 0x61, 0x2f, 0xe1, 0x48, 0xe1, 0xc6, 0x5e, 0x52, 0xe3, 0x78,
	0xdb, 0x74, 0xe8, 0x9a, 0xfe, 0x9d, 0x20, 0x9d, 0xa5, 0x15, 0x76, 0x55, 0x3a, 0x0f, 0xc3, 0xc4,
	0x23, 0x9a, 0x83, 0xd1, 0x19, 0xf2, 0x51, 0xb5, 0xd9, 0x14, 0xb3, 0x08, 0x0e, 0xf2, 0x6a, 0xef,
	0xaa, 0x85, 0x3b, 0x70, 0xb9, 0x0e, 0xc7, 0x66, 0x70, 0x98, 0x8b, 0xcd, 0x55, 0xbb, 0x6c, 0xec,
	0xca, 0x1e, 0xd2, 0x74, 0x87, 0x17, 0x06, 0x85, 0xc5, 0x4f, 0x32, 0x47, 0xfe, 0xc4, 0x15, 0xb5,
	0x18, 0x9a, 0x49, 0xf9, 0x45, 0x18, 0xa4, 0xb1, 0x1f, 0x56, 0x2e, 0x6d, 0x31, 0x2d, 0x8e, 0x54,
	0x6b, 0x69, 0x5d, 0x72, 0x52, 0x2d, 0x4e, 0x4d, 0xb4, 0x6e, 0xdb, 0x51, 0xe7, 0xb6, 0x35, 0x6b,
	0xcc, 0xda, 0x6b, 0x7c, 0xf6, 0x23, 0x80, 0x03, 0xb7, 0xac, 0x1f, 0xd1, 0xac, 0xc9, 0xa4, 0x0b,
	0x18, 0x77, 0x1e, 0x29, 0x76, 0xda, 0xbe, 0x3a, 0x0f, 0xdf, 0xaf, 0x93, 0x67, 0x8f, 0x5e, 0xd7,
	0x68, 0x87, 0xbd, 0x81, 0x71, 0xe7, 0xcd, 0xec, 0xf6, 0x79, 0xf8, 0x9c, 0x9e, 0x1c, 0xb6, 0xb3,
	0xf4, 0xe6, 0xee, 0xdc, 0x0e, 0xdc, 0x7b, 0xfc, 0xea, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1,
	0x1b, 0x47, 0x77, 0x9e, 0x05, 0x00, 0x00,
}
