// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MetaGateway.proto

package MetaGateway

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 100以内都是客户端主动发送的
// 100-200是服务端主动发送的
type CmdId int32

const (
	CmdId_UnKnown                     CmdId = 0
	CmdId_PingCmdId                   CmdId = 1
	CmdId_PongCmdId                   CmdId = 2
	CmdId_LoginReqCmdId               CmdId = 11
	CmdId_LoginRespCmdId              CmdId = 12
	CmdId_LoginAckCmdId               CmdId = 13
	CmdId_LogoutReqCmdId              CmdId = 15
	CmdId_LogoutRespCmdId             CmdId = 16
	CmdId_ClientStateEventReqCmdId    CmdId = 21
	CmdId_ClientStateEventRespCmdId   CmdId = 22
	CmdId_ClientSendGiftReqCmdId      CmdId = 23
	CmdId_ClientSendGiftRespCmdId     CmdId = 24
	CmdId_SendMessageReqCmdId         CmdId = 31
	CmdId_SendMessageRespCmdId        CmdId = 32
	CmdId_SyncMessageReqCmdId         CmdId = 33
	CmdId_SyncMessageRespCmdId        CmdId = 34
	CmdId_SyncHistoryMessageReqCmdId  CmdId = 35
	CmdId_SyncHistoryMessageRespCmdId CmdId = 36
	//小游戏
	CmdId_ClientPassThroughEventReqCmdId     CmdId = 45
	CmdId_ClientPassThroughEventRespCmdId    CmdId = 46
	CmdId_BroadcastStateEventReqCmdId        CmdId = 101
	CmdId_BroadcastStateEventRespCmdId       CmdId = 102
	CmdId_SceneChangeReqCmdId                CmdId = 103
	CmdId_SceneChangeRespCmdId               CmdId = 104
	CmdId_BroadcastSendGiftReqCmdId          CmdId = 105
	CmdId_BroadcastPassThroughEventReqCmdId  CmdId = 109
	CmdId_BroadcastPassThroughEventRespCmdId CmdId = 110
	CmdId_SyncMessageNotifyCmdId             CmdId = 191
)

var CmdId_name = map[int32]string{
	0:   "UnKnown",
	1:   "PingCmdId",
	2:   "PongCmdId",
	11:  "LoginReqCmdId",
	12:  "LoginRespCmdId",
	13:  "LoginAckCmdId",
	15:  "LogoutReqCmdId",
	16:  "LogoutRespCmdId",
	21:  "ClientStateEventReqCmdId",
	22:  "ClientStateEventRespCmdId",
	23:  "ClientSendGiftReqCmdId",
	24:  "ClientSendGiftRespCmdId",
	31:  "SendMessageReqCmdId",
	32:  "SendMessageRespCmdId",
	33:  "SyncMessageReqCmdId",
	34:  "SyncMessageRespCmdId",
	35:  "SyncHistoryMessageReqCmdId",
	36:  "SyncHistoryMessageRespCmdId",
	45:  "ClientPassThroughEventReqCmdId",
	46:  "ClientPassThroughEventRespCmdId",
	101: "BroadcastStateEventReqCmdId",
	102: "BroadcastStateEventRespCmdId",
	103: "SceneChangeReqCmdId",
	104: "SceneChangeRespCmdId",
	105: "BroadcastSendGiftReqCmdId",
	109: "BroadcastPassThroughEventReqCmdId",
	110: "BroadcastPassThroughEventRespCmdId",
	191: "SyncMessageNotifyCmdId",
}

var CmdId_value = map[string]int32{
	"UnKnown":                            0,
	"PingCmdId":                          1,
	"PongCmdId":                          2,
	"LoginReqCmdId":                      11,
	"LoginRespCmdId":                     12,
	"LoginAckCmdId":                      13,
	"LogoutReqCmdId":                     15,
	"LogoutRespCmdId":                    16,
	"ClientStateEventReqCmdId":           21,
	"ClientStateEventRespCmdId":          22,
	"ClientSendGiftReqCmdId":             23,
	"ClientSendGiftRespCmdId":            24,
	"SendMessageReqCmdId":                31,
	"SendMessageRespCmdId":               32,
	"SyncMessageReqCmdId":                33,
	"SyncMessageRespCmdId":               34,
	"SyncHistoryMessageReqCmdId":         35,
	"SyncHistoryMessageRespCmdId":        36,
	"ClientPassThroughEventReqCmdId":     45,
	"ClientPassThroughEventRespCmdId":    46,
	"BroadcastStateEventReqCmdId":        101,
	"BroadcastStateEventRespCmdId":       102,
	"SceneChangeReqCmdId":                103,
	"SceneChangeRespCmdId":               104,
	"BroadcastSendGiftReqCmdId":          105,
	"BroadcastPassThroughEventReqCmdId":  109,
	"BroadcastPassThroughEventRespCmdId": 110,
	"SyncMessageNotifyCmdId":             191,
}

func (x CmdId) String() string {
	return proto.EnumName(CmdId_name, int32(x))
}

func (CmdId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{0}
}

type Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nil) Reset()         { *m = Nil{} }
func (m *Nil) String() string { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()    {}
func (*Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{0}
}

func (m *Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nil.Unmarshal(m, b)
}
func (m *Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nil.Marshal(b, m, deterministic)
}
func (m *Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nil.Merge(m, src)
}
func (m *Nil) XXX_Size() int {
	return xxx_messageInfo_Nil.Size(m)
}
func (m *Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Nil proto.InternalMessageInfo

// 基本数据格式，可以接收所有的数据报文，用来处理一些基础逻辑（比如：全局打印日志、对reqId做重复检测）
type BaseReq struct {
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseReq) Reset()         { *m = BaseReq{} }
func (m *BaseReq) String() string { return proto.CompactTextString(m) }
func (*BaseReq) ProtoMessage()    {}
func (*BaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{1}
}

func (m *BaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseReq.Unmarshal(m, b)
}
func (m *BaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseReq.Marshal(b, m, deterministic)
}
func (m *BaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseReq.Merge(m, src)
}
func (m *BaseReq) XXX_Size() int {
	return xxx_messageInfo_BaseReq.Size(m)
}
func (m *BaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_BaseReq proto.InternalMessageInfo

func (m *BaseReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type BaseResp struct {
	RespId               int64    `protobuf:"varint,101,opt,name=respId,proto3" json:"respId,omitempty"`
	Code                 int32    `protobuf:"varint,102,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,103,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResp) Reset()         { *m = BaseResp{} }
func (m *BaseResp) String() string { return proto.CompactTextString(m) }
func (*BaseResp) ProtoMessage()    {}
func (*BaseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{2}
}

func (m *BaseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResp.Unmarshal(m, b)
}
func (m *BaseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResp.Marshal(b, m, deterministic)
}
func (m *BaseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResp.Merge(m, src)
}
func (m *BaseResp) XXX_Size() int {
	return xxx_messageInfo_BaseResp.Size(m)
}
func (m *BaseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResp.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResp proto.InternalMessageInfo

func (m *BaseResp) GetRespId() int64 {
	if m != nil {
		return m.RespId
	}
	return 0
}

func (m *BaseResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BaseResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Ping struct {
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{3}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type Pong struct {
	Ts                   int64    `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	RespId               int64    `protobuf:"varint,101,opt,name=respId,proto3" json:"respId,omitempty"`
	Code                 int32    `protobuf:"varint,102,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,103,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{4}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *Pong) GetRespId() int64 {
	if m != nil {
		return m.RespId
	}
	return 0
}

func (m *Pong) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Pong) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 登陆
type LoginReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AesKey               []byte   `protobuf:"bytes,3,opt,name=aesKey,proto3" json:"aesKey,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	LoginType            int32    `protobuf:"varint,5,opt,name=loginType,proto3" json:"loginType,omitempty"`
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{5}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginReq) GetAesKey() []byte {
	if m != nil {
		return m.AesKey
	}
	return nil
}

func (m *LoginReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *LoginReq) GetLoginType() int32 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

func (m *LoginReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type LoginResp struct {
	RespId               int64    `protobuf:"varint,101,opt,name=respId,proto3" json:"respId,omitempty"`
	Code                 int32    `protobuf:"varint,102,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,103,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{6}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetRespId() int64 {
	if m != nil {
		return m.RespId
	}
	return 0
}

func (m *LoginResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LoginAck struct {
	LoginType            int32    `protobuf:"varint,5,opt,name=loginType,proto3" json:"loginType,omitempty"`
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAck) Reset()         { *m = LoginAck{} }
func (m *LoginAck) String() string { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()    {}
func (*LoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{7}
}

func (m *LoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAck.Unmarshal(m, b)
}
func (m *LoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAck.Marshal(b, m, deterministic)
}
func (m *LoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAck.Merge(m, src)
}
func (m *LoginAck) XXX_Size() int {
	return xxx_messageInfo_LoginAck.Size(m)
}
func (m *LoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAck proto.InternalMessageInfo

func (m *LoginAck) GetLoginType() int32 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

func (m *LoginAck) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type LogoutReq struct {
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{8}
}

func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (m *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(m, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

func (m *LogoutReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type LogoutResp struct {
	RespId               int64    `protobuf:"varint,101,opt,name=respId,proto3" json:"respId,omitempty"`
	Code                 int32    `protobuf:"varint,102,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,103,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResp) Reset()         { *m = LogoutResp{} }
func (m *LogoutResp) String() string { return proto.CompactTextString(m) }
func (*LogoutResp) ProtoMessage()    {}
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{9}
}

func (m *LogoutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResp.Unmarshal(m, b)
}
func (m *LogoutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResp.Marshal(b, m, deterministic)
}
func (m *LogoutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResp.Merge(m, src)
}
func (m *LogoutResp) XXX_Size() int {
	return xxx_messageInfo_LogoutResp.Size(m)
}
func (m *LogoutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResp.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResp proto.InternalMessageInfo

func (m *LogoutResp) GetRespId() int64 {
	if m != nil {
		return m.RespId
	}
	return 0
}

func (m *LogoutResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LogoutResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// ↓↓↓↓↓↓↓↓↓↓↓ im相关 ↓↓↓↓↓↓↓↓↓↓
type SendMessageReq struct {
	MessageType          int32    `protobuf:"varint,1,opt,name=messageType,proto3" json:"messageType,omitempty"`
	ClientMsgId          string   `protobuf:"bytes,4,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ConvId               string   `protobuf:"bytes,7,opt,name=convId,proto3" json:"convId,omitempty"`
	ConvType             int32    `protobuf:"varint,8,opt,name=convType,proto3" json:"convType,omitempty"`
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageReq) Reset()         { *m = SendMessageReq{} }
func (m *SendMessageReq) String() string { return proto.CompactTextString(m) }
func (*SendMessageReq) ProtoMessage()    {}
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{10}
}

func (m *SendMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageReq.Unmarshal(m, b)
}
func (m *SendMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageReq.Marshal(b, m, deterministic)
}
func (m *SendMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageReq.Merge(m, src)
}
func (m *SendMessageReq) XXX_Size() int {
	return xxx_messageInfo_SendMessageReq.Size(m)
}
func (m *SendMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageReq proto.InternalMessageInfo

func (m *SendMessageReq) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *SendMessageReq) GetClientMsgId() string {
	if m != nil {
		return m.ClientMsgId
	}
	return ""
}

func (m *SendMessageReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SendMessageReq) GetConvId() string {
	if m != nil {
		return m.ConvId
	}
	return ""
}

func (m *SendMessageReq) GetConvType() int32 {
	if m != nil {
		return m.ConvType
	}
	return 0
}

func (m *SendMessageReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type SendMessageResp struct {
	ServerMsgId          string   `protobuf:"bytes,1,opt,name=serverMsgId,proto3" json:"serverMsgId,omitempty"`
	ClientMsgId          string   `protobuf:"bytes,4,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`
	RespId               int64    `protobuf:"varint,101,opt,name=respId,proto3" json:"respId,omitempty"`
	Code                 int32    `protobuf:"varint,102,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,103,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResp) Reset()         { *m = SendMessageResp{} }
func (m *SendMessageResp) String() string { return proto.CompactTextString(m) }
func (*SendMessageResp) ProtoMessage()    {}
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{11}
}

func (m *SendMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResp.Unmarshal(m, b)
}
func (m *SendMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResp.Marshal(b, m, deterministic)
}
func (m *SendMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResp.Merge(m, src)
}
func (m *SendMessageResp) XXX_Size() int {
	return xxx_messageInfo_SendMessageResp.Size(m)
}
func (m *SendMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResp proto.InternalMessageInfo

func (m *SendMessageResp) GetServerMsgId() string {
	if m != nil {
		return m.ServerMsgId
	}
	return ""
}

func (m *SendMessageResp) GetClientMsgId() string {
	if m != nil {
		return m.ClientMsgId
	}
	return ""
}

func (m *SendMessageResp) GetRespId() int64 {
	if m != nil {
		return m.RespId
	}
	return 0
}

func (m *SendMessageResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SendMessageResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Message struct {
	ConvId               string   `protobuf:"bytes,1,opt,name=convId,proto3" json:"convId,omitempty"`
	ConvType             int32    `protobuf:"varint,2,opt,name=convType,proto3" json:"convType,omitempty"`
	Cursor               int64    `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	MessageType          int32    `protobuf:"varint,4,opt,name=messageType,proto3" json:"messageType,omitempty"`
	SenderId             int32    `protobuf:"varint,5,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ClientMsgId          string   `protobuf:"bytes,7,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`
	ServerMsgId          string   `protobuf:"bytes,8,opt,name=serverMsgId,proto3" json:"serverMsgId,omitempty"`
	Content              string   `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt            int64    `protobuf:"varint,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{12}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetConvId() string {
	if m != nil {
		return m.ConvId
	}
	return ""
}

func (m *Message) GetConvType() int32 {
	if m != nil {
		return m.ConvType
	}
	return 0
}

func (m *Message) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *Message) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *Message) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Message) GetClientMsgId() string {
	if m != nil {
		return m.ClientMsgId
	}
	return ""
}

func (m *Message) GetServerMsgId() string {
	if m != nil {
		return m.ServerMsgId
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type SyncMessageReq struct {
	ConvType             int32    `protobuf:"varint,2,opt,name=convType,proto3" json:"convType,omitempty"`
	Cursor               int64    `protobuf:"varint,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncMessageReq) Reset()         { *m = SyncMessageReq{} }
func (m *SyncMessageReq) String() string { return proto.CompactTextString(m) }
func (*SyncMessageReq) ProtoMessage()    {}
func (*SyncMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{13}
}

func (m *SyncMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessageReq.Unmarshal(m, b)
}
func (m *SyncMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessageReq.Marshal(b, m, deterministic)
}
func (m *SyncMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessageReq.Merge(m, src)
}
func (m *SyncMessageReq) XXX_Size() int {
	return xxx_messageInfo_SyncMessageReq.Size(m)
}
func (m *SyncMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessageReq proto.InternalMessageInfo

func (m *SyncMessageReq) GetConvType() int32 {
	if m != nil {
		return m.ConvType
	}
	return 0
}

func (m *SyncMessageReq) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *SyncMessageReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type SyncMessageResp struct {
	Msgs                 []*Message `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
	More                 int32      `protobuf:"varint,2,opt,name=more,proto3" json:"more,omitempty"`
	ConvType             int32      `protobuf:"varint,3,opt,name=convType,proto3" json:"convType,omitempty"`
	RespId               int64      `protobuf:"varint,101,opt,name=respId,proto3" json:"respId,omitempty"`
	Code                 int32      `protobuf:"varint,102,opt,name=code,proto3" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,103,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SyncMessageResp) Reset()         { *m = SyncMessageResp{} }
func (m *SyncMessageResp) String() string { return proto.CompactTextString(m) }
func (*SyncMessageResp) ProtoMessage()    {}
func (*SyncMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{14}
}

func (m *SyncMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessageResp.Unmarshal(m, b)
}
func (m *SyncMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessageResp.Marshal(b, m, deterministic)
}
func (m *SyncMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessageResp.Merge(m, src)
}
func (m *SyncMessageResp) XXX_Size() int {
	return xxx_messageInfo_SyncMessageResp.Size(m)
}
func (m *SyncMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessageResp proto.InternalMessageInfo

func (m *SyncMessageResp) GetMsgs() []*Message {
	if m != nil {
		return m.Msgs
	}
	return nil
}

func (m *SyncMessageResp) GetMore() int32 {
	if m != nil {
		return m.More
	}
	return 0
}

func (m *SyncMessageResp) GetConvType() int32 {
	if m != nil {
		return m.ConvType
	}
	return 0
}

func (m *SyncMessageResp) GetRespId() int64 {
	if m != nil {
		return m.RespId
	}
	return 0
}

func (m *SyncMessageResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SyncMessageResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SyncHistoryMessageReq struct {
	UserId               int32    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	ConvId               string   `protobuf:"bytes,4,opt,name=convId,proto3" json:"convId,omitempty"`
	Cursor               int64    `protobuf:"varint,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	MessageType          []int32  `protobuf:"varint,6,rep,packed,name=messageType,proto3" json:"messageType,omitempty"`
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncHistoryMessageReq) Reset()         { *m = SyncHistoryMessageReq{} }
func (m *SyncHistoryMessageReq) String() string { return proto.CompactTextString(m) }
func (*SyncHistoryMessageReq) ProtoMessage()    {}
func (*SyncHistoryMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{15}
}

func (m *SyncHistoryMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncHistoryMessageReq.Unmarshal(m, b)
}
func (m *SyncHistoryMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncHistoryMessageReq.Marshal(b, m, deterministic)
}
func (m *SyncHistoryMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncHistoryMessageReq.Merge(m, src)
}
func (m *SyncHistoryMessageReq) XXX_Size() int {
	return xxx_messageInfo_SyncHistoryMessageReq.Size(m)
}
func (m *SyncHistoryMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncHistoryMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncHistoryMessageReq proto.InternalMessageInfo

func (m *SyncHistoryMessageReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SyncHistoryMessageReq) GetConvId() string {
	if m != nil {
		return m.ConvId
	}
	return ""
}

func (m *SyncHistoryMessageReq) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *SyncHistoryMessageReq) GetMessageType() []int32 {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (m *SyncHistoryMessageReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type SyncHistoryMessageResp struct {
	Msgs                 []*Message `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
	RespId               int64      `protobuf:"varint,101,opt,name=respId,proto3" json:"respId,omitempty"`
	Code                 int32      `protobuf:"varint,102,opt,name=code,proto3" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,103,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SyncHistoryMessageResp) Reset()         { *m = SyncHistoryMessageResp{} }
func (m *SyncHistoryMessageResp) String() string { return proto.CompactTextString(m) }
func (*SyncHistoryMessageResp) ProtoMessage()    {}
func (*SyncHistoryMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{16}
}

func (m *SyncHistoryMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncHistoryMessageResp.Unmarshal(m, b)
}
func (m *SyncHistoryMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncHistoryMessageResp.Marshal(b, m, deterministic)
}
func (m *SyncHistoryMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncHistoryMessageResp.Merge(m, src)
}
func (m *SyncHistoryMessageResp) XXX_Size() int {
	return xxx_messageInfo_SyncHistoryMessageResp.Size(m)
}
func (m *SyncHistoryMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncHistoryMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncHistoryMessageResp proto.InternalMessageInfo

func (m *SyncHistoryMessageResp) GetMsgs() []*Message {
	if m != nil {
		return m.Msgs
	}
	return nil
}

func (m *SyncHistoryMessageResp) GetRespId() int64 {
	if m != nil {
		return m.RespId
	}
	return 0
}

func (m *SyncHistoryMessageResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SyncHistoryMessageResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SyncMessageNotifyReq struct {
	ConvType             int32    `protobuf:"varint,1,opt,name=convType,proto3" json:"convType,omitempty"`
	TargetUserId         []int32  `protobuf:"varint,2,rep,packed,name=targetUserId,proto3" json:"targetUserId,omitempty"`
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncMessageNotifyReq) Reset()         { *m = SyncMessageNotifyReq{} }
func (m *SyncMessageNotifyReq) String() string { return proto.CompactTextString(m) }
func (*SyncMessageNotifyReq) ProtoMessage()    {}
func (*SyncMessageNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{17}
}

func (m *SyncMessageNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessageNotifyReq.Unmarshal(m, b)
}
func (m *SyncMessageNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessageNotifyReq.Marshal(b, m, deterministic)
}
func (m *SyncMessageNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessageNotifyReq.Merge(m, src)
}
func (m *SyncMessageNotifyReq) XXX_Size() int {
	return xxx_messageInfo_SyncMessageNotifyReq.Size(m)
}
func (m *SyncMessageNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessageNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessageNotifyReq proto.InternalMessageInfo

func (m *SyncMessageNotifyReq) GetConvType() int32 {
	if m != nil {
		return m.ConvType
	}
	return 0
}

func (m *SyncMessageNotifyReq) GetTargetUserId() []int32 {
	if m != nil {
		return m.TargetUserId
	}
	return nil
}

func (m *SyncMessageNotifyReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

// ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ 状态同步相关 ↓ ↓ ↓ ↓
//
//	message Point{
//	 float x = 1;
//	 float y = 2;
//	 float z = 3;
//	}
//
// 用户属性
type UserStateEvent struct {
	//  Point endPoint = 1; //寻路终点
	//  repeated Point pathPoint = 2; //路径点  当用户寻路发生变化时会更新寻路点，内容是所有的途经点
	//  Point now = 3; //用户当前位置
	//  int32 action = 4; // 动作：1-移动；2-停止
	X                    float32   `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32   `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32   `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Direction            []float32 `protobuf:"fixed32,4,rep,packed,name=direction,proto3" json:"direction,omitempty"`
	OnlineStatus         int32     `protobuf:"varint,7,opt,name=onlineStatus,proto3" json:"onlineStatus,omitempty"`
	UserId               int32     `protobuf:"varint,8,opt,name=userId,proto3" json:"userId,omitempty"`
	ActionStatus         string    `protobuf:"bytes,10,opt,name=actionStatus,proto3" json:"actionStatus,omitempty"`
	From                 int32     `protobuf:"varint,11,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserStateEvent) Reset()         { *m = UserStateEvent{} }
func (m *UserStateEvent) String() string { return proto.CompactTextString(m) }
func (*UserStateEvent) ProtoMessage()    {}
func (*UserStateEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{18}
}

func (m *UserStateEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStateEvent.Unmarshal(m, b)
}
func (m *UserStateEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStateEvent.Marshal(b, m, deterministic)
}
func (m *UserStateEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStateEvent.Merge(m, src)
}
func (m *UserStateEvent) XXX_Size() int {
	return xxx_messageInfo_UserStateEvent.Size(m)
}
func (m *UserStateEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStateEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UserStateEvent proto.InternalMessageInfo

func (m *UserStateEvent) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *UserStateEvent) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *UserStateEvent) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *UserStateEvent) GetDirection() []float32 {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *UserStateEvent) GetOnlineStatus() int32 {
	if m != nil {
		return m.OnlineStatus
	}
	return 0
}

func (m *UserStateEvent) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserStateEvent) GetActionStatus() string {
	if m != nil {
		return m.ActionStatus
	}
	return ""
}

func (m *UserStateEvent) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

// 场景变化
type SceneChangeReq struct {
	SceneType int32  `protobuf:"varint,1,opt,name=sceneType,proto3" json:"sceneType,omitempty"`
	SceneId   string `protobuf:"bytes,2,opt,name=sceneId,proto3" json:"sceneId,omitempty"`
	//  string rtcId = 3; //rtcId
	//  string chatId = 5; //聊天室Id
	//  string convId = 7; //会话id
	Exit                 int32    `protobuf:"varint,6,opt,name=exit,proto3" json:"exit,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SceneChangeReq) Reset()         { *m = SceneChangeReq{} }
func (m *SceneChangeReq) String() string { return proto.CompactTextString(m) }
func (*SceneChangeReq) ProtoMessage()    {}
func (*SceneChangeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{19}
}

func (m *SceneChangeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneChangeReq.Unmarshal(m, b)
}
func (m *SceneChangeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneChangeReq.Marshal(b, m, deterministic)
}
func (m *SceneChangeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneChangeReq.Merge(m, src)
}
func (m *SceneChangeReq) XXX_Size() int {
	return xxx_messageInfo_SceneChangeReq.Size(m)
}
func (m *SceneChangeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneChangeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SceneChangeReq proto.InternalMessageInfo

func (m *SceneChangeReq) GetSceneType() int32 {
	if m != nil {
		return m.SceneType
	}
	return 0
}

func (m *SceneChangeReq) GetSceneId() string {
	if m != nil {
		return m.SceneId
	}
	return ""
}

func (m *SceneChangeReq) GetExit() int32 {
	if m != nil {
		return m.Exit
	}
	return 0
}

func (m *SceneChangeReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SceneChangeReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

// 闯关游戏
type PassThroughUser struct {
	User                 *UserStateEvent `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Pass                 int32           `protobuf:"varint,2,opt,name=pass,proto3" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PassThroughUser) Reset()         { *m = PassThroughUser{} }
func (m *PassThroughUser) String() string { return proto.CompactTextString(m) }
func (*PassThroughUser) ProtoMessage()    {}
func (*PassThroughUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{20}
}

func (m *PassThroughUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassThroughUser.Unmarshal(m, b)
}
func (m *PassThroughUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassThroughUser.Marshal(b, m, deterministic)
}
func (m *PassThroughUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassThroughUser.Merge(m, src)
}
func (m *PassThroughUser) XXX_Size() int {
	return xxx_messageInfo_PassThroughUser.Size(m)
}
func (m *PassThroughUser) XXX_DiscardUnknown() {
	xxx_messageInfo_PassThroughUser.DiscardUnknown(m)
}

var xxx_messageInfo_PassThroughUser proto.InternalMessageInfo

func (m *PassThroughUser) GetUser() *UserStateEvent {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PassThroughUser) GetPass() int32 {
	if m != nil {
		return m.Pass
	}
	return 0
}

type PassThroughLevel struct {
	LevelId              int32                             `protobuf:"varint,1,opt,name=levelId,proto3" json:"levelId,omitempty"`
	Fifth                map[string]*PassThroughLevelFifth `protobuf:"bytes,3,rep,name=fifth,proto3" json:"fifth,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *PassThroughLevel) Reset()         { *m = PassThroughLevel{} }
func (m *PassThroughLevel) String() string { return proto.CompactTextString(m) }
func (*PassThroughLevel) ProtoMessage()    {}
func (*PassThroughLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{21}
}

func (m *PassThroughLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassThroughLevel.Unmarshal(m, b)
}
func (m *PassThroughLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassThroughLevel.Marshal(b, m, deterministic)
}
func (m *PassThroughLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassThroughLevel.Merge(m, src)
}
func (m *PassThroughLevel) XXX_Size() int {
	return xxx_messageInfo_PassThroughLevel.Size(m)
}
func (m *PassThroughLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_PassThroughLevel.DiscardUnknown(m)
}

var xxx_messageInfo_PassThroughLevel proto.InternalMessageInfo

func (m *PassThroughLevel) GetLevelId() int32 {
	if m != nil {
		return m.LevelId
	}
	return 0
}

func (m *PassThroughLevel) GetFifth() map[string]*PassThroughLevelFifth {
	if m != nil {
		return m.Fifth
	}
	return nil
}

type PassThroughLevelFifth struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    float32  `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	IsReal               int32    `protobuf:"varint,5,opt,name=isReal,proto3" json:"isReal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassThroughLevelFifth) Reset()         { *m = PassThroughLevelFifth{} }
func (m *PassThroughLevelFifth) String() string { return proto.CompactTextString(m) }
func (*PassThroughLevelFifth) ProtoMessage()    {}
func (*PassThroughLevelFifth) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{22}
}

func (m *PassThroughLevelFifth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassThroughLevelFifth.Unmarshal(m, b)
}
func (m *PassThroughLevelFifth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassThroughLevelFifth.Marshal(b, m, deterministic)
}
func (m *PassThroughLevelFifth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassThroughLevelFifth.Merge(m, src)
}
func (m *PassThroughLevelFifth) XXX_Size() int {
	return xxx_messageInfo_PassThroughLevelFifth.Size(m)
}
func (m *PassThroughLevelFifth) XXX_DiscardUnknown() {
	xxx_messageInfo_PassThroughLevelFifth.DiscardUnknown(m)
}

var xxx_messageInfo_PassThroughLevelFifth proto.InternalMessageInfo

func (m *PassThroughLevelFifth) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PassThroughLevelFifth) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PassThroughLevelFifth) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *PassThroughLevelFifth) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *PassThroughLevelFifth) GetIsReal() int32 {
	if m != nil {
		return m.IsReal
	}
	return 0
}

type ClientPassThroughEventReq struct {
	User                 *PassThroughUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ReqId                int64            `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ClientPassThroughEventReq) Reset()         { *m = ClientPassThroughEventReq{} }
func (m *ClientPassThroughEventReq) String() string { return proto.CompactTextString(m) }
func (*ClientPassThroughEventReq) ProtoMessage()    {}
func (*ClientPassThroughEventReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{23}
}

func (m *ClientPassThroughEventReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPassThroughEventReq.Unmarshal(m, b)
}
func (m *ClientPassThroughEventReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPassThroughEventReq.Marshal(b, m, deterministic)
}
func (m *ClientPassThroughEventReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPassThroughEventReq.Merge(m, src)
}
func (m *ClientPassThroughEventReq) XXX_Size() int {
	return xxx_messageInfo_ClientPassThroughEventReq.Size(m)
}
func (m *ClientPassThroughEventReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPassThroughEventReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPassThroughEventReq proto.InternalMessageInfo

func (m *ClientPassThroughEventReq) GetUser() *PassThroughUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ClientPassThroughEventReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type BroadcastPassThroughEventReq struct {
	Level                  map[int32]*PassThroughLevel `protobuf:"bytes,1,rep,name=level,proto3" json:"level,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	User                   []*PassThroughUser          `protobuf:"bytes,2,rep,name=user,proto3" json:"user,omitempty"`
	GameBeginTimeRemaining int64                       `protobuf:"varint,5,opt,name=gameBeginTimeRemaining,proto3" json:"gameBeginTimeRemaining,omitempty"`
	GameState              int32                       `protobuf:"varint,6,opt,name=gameState,proto3" json:"gameState,omitempty"`
	TargetUserIds          []int32                     `protobuf:"varint,10,rep,packed,name=targetUserIds,proto3" json:"targetUserIds,omitempty"`
	ReqId                  int64                       `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                    `json:"-"`
	XXX_unrecognized       []byte                      `json:"-"`
	XXX_sizecache          int32                       `json:"-"`
}

func (m *BroadcastPassThroughEventReq) Reset()         { *m = BroadcastPassThroughEventReq{} }
func (m *BroadcastPassThroughEventReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastPassThroughEventReq) ProtoMessage()    {}
func (*BroadcastPassThroughEventReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{24}
}

func (m *BroadcastPassThroughEventReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastPassThroughEventReq.Unmarshal(m, b)
}
func (m *BroadcastPassThroughEventReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastPassThroughEventReq.Marshal(b, m, deterministic)
}
func (m *BroadcastPassThroughEventReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastPassThroughEventReq.Merge(m, src)
}
func (m *BroadcastPassThroughEventReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastPassThroughEventReq.Size(m)
}
func (m *BroadcastPassThroughEventReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastPassThroughEventReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastPassThroughEventReq proto.InternalMessageInfo

func (m *BroadcastPassThroughEventReq) GetLevel() map[int32]*PassThroughLevel {
	if m != nil {
		return m.Level
	}
	return nil
}

func (m *BroadcastPassThroughEventReq) GetUser() []*PassThroughUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BroadcastPassThroughEventReq) GetGameBeginTimeRemaining() int64 {
	if m != nil {
		return m.GameBeginTimeRemaining
	}
	return 0
}

func (m *BroadcastPassThroughEventReq) GetGameState() int32 {
	if m != nil {
		return m.GameState
	}
	return 0
}

func (m *BroadcastPassThroughEventReq) GetTargetUserIds() []int32 {
	if m != nil {
		return m.TargetUserIds
	}
	return nil
}

func (m *BroadcastPassThroughEventReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

// 卡座包厢
type Box struct {
	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubspaceId string `protobuf:"bytes,2,opt,name=subspaceId,proto3" json:"subspaceId,omitempty"`
	//  string rtcId = 3; //
	Seat                 map[int32]int32 `protobuf:"bytes,4,rep,name=seat,proto3" json:"seat,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Box) Reset()         { *m = Box{} }
func (m *Box) String() string { return proto.CompactTextString(m) }
func (*Box) ProtoMessage()    {}
func (*Box) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{25}
}

func (m *Box) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Box.Unmarshal(m, b)
}
func (m *Box) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Box.Marshal(b, m, deterministic)
}
func (m *Box) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Box.Merge(m, src)
}
func (m *Box) XXX_Size() int {
	return xxx_messageInfo_Box.Size(m)
}
func (m *Box) XXX_DiscardUnknown() {
	xxx_messageInfo_Box.DiscardUnknown(m)
}

var xxx_messageInfo_Box proto.InternalMessageInfo

func (m *Box) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Box) GetSubspaceId() string {
	if m != nil {
		return m.SubspaceId
	}
	return ""
}

func (m *Box) GetSeat() map[int32]int32 {
	if m != nil {
		return m.Seat
	}
	return nil
}

// 客户端状态变化
type ClientStateEventReq struct {
	User                 *UserStateEvent `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ReqId                int64           `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClientStateEventReq) Reset()         { *m = ClientStateEventReq{} }
func (m *ClientStateEventReq) String() string { return proto.CompactTextString(m) }
func (*ClientStateEventReq) ProtoMessage()    {}
func (*ClientStateEventReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{26}
}

func (m *ClientStateEventReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientStateEventReq.Unmarshal(m, b)
}
func (m *ClientStateEventReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientStateEventReq.Marshal(b, m, deterministic)
}
func (m *ClientStateEventReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientStateEventReq.Merge(m, src)
}
func (m *ClientStateEventReq) XXX_Size() int {
	return xxx_messageInfo_ClientStateEventReq.Size(m)
}
func (m *ClientStateEventReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientStateEventReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClientStateEventReq proto.InternalMessageInfo

func (m *ClientStateEventReq) GetUser() *UserStateEvent {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ClientStateEventReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type ClientStateEventResp struct {
	RespId               int64    `protobuf:"varint,101,opt,name=respId,proto3" json:"respId,omitempty"`
	Code                 int32    `protobuf:"varint,102,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,103,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientStateEventResp) Reset()         { *m = ClientStateEventResp{} }
func (m *ClientStateEventResp) String() string { return proto.CompactTextString(m) }
func (*ClientStateEventResp) ProtoMessage()    {}
func (*ClientStateEventResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{27}
}

func (m *ClientStateEventResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientStateEventResp.Unmarshal(m, b)
}
func (m *ClientStateEventResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientStateEventResp.Marshal(b, m, deterministic)
}
func (m *ClientStateEventResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientStateEventResp.Merge(m, src)
}
func (m *ClientStateEventResp) XXX_Size() int {
	return xxx_messageInfo_ClientStateEventResp.Size(m)
}
func (m *ClientStateEventResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientStateEventResp.DiscardUnknown(m)
}

var xxx_messageInfo_ClientStateEventResp proto.InternalMessageInfo

func (m *ClientStateEventResp) GetRespId() int64 {
	if m != nil {
		return m.RespId
	}
	return 0
}

func (m *ClientStateEventResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ClientStateEventResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 服务端同步状态变化
type BroadcastStateEventReq struct {
	User                 []*UserStateEvent `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	Box                  map[string]*Box   `protobuf:"bytes,2,rep,name=box,proto3" json:"box,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TargetUserIds        []int32           `protobuf:"varint,4,rep,packed,name=targetUserIds,proto3" json:"targetUserIds,omitempty"`
	ReqId                int64             `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BroadcastStateEventReq) Reset()         { *m = BroadcastStateEventReq{} }
func (m *BroadcastStateEventReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastStateEventReq) ProtoMessage()    {}
func (*BroadcastStateEventReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{28}
}

func (m *BroadcastStateEventReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastStateEventReq.Unmarshal(m, b)
}
func (m *BroadcastStateEventReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastStateEventReq.Marshal(b, m, deterministic)
}
func (m *BroadcastStateEventReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastStateEventReq.Merge(m, src)
}
func (m *BroadcastStateEventReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastStateEventReq.Size(m)
}
func (m *BroadcastStateEventReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastStateEventReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastStateEventReq proto.InternalMessageInfo

func (m *BroadcastStateEventReq) GetUser() []*UserStateEvent {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BroadcastStateEventReq) GetBox() map[string]*Box {
	if m != nil {
		return m.Box
	}
	return nil
}

func (m *BroadcastStateEventReq) GetTargetUserIds() []int32 {
	if m != nil {
		return m.TargetUserIds
	}
	return nil
}

func (m *BroadcastStateEventReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type BroadcastStateEventResp struct {
	RespId               int64    `protobuf:"varint,101,opt,name=respId,proto3" json:"respId,omitempty"`
	Code                 int32    `protobuf:"varint,102,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,103,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastStateEventResp) Reset()         { *m = BroadcastStateEventResp{} }
func (m *BroadcastStateEventResp) String() string { return proto.CompactTextString(m) }
func (*BroadcastStateEventResp) ProtoMessage()    {}
func (*BroadcastStateEventResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{29}
}

func (m *BroadcastStateEventResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastStateEventResp.Unmarshal(m, b)
}
func (m *BroadcastStateEventResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastStateEventResp.Marshal(b, m, deterministic)
}
func (m *BroadcastStateEventResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastStateEventResp.Merge(m, src)
}
func (m *BroadcastStateEventResp) XXX_Size() int {
	return xxx_messageInfo_BroadcastStateEventResp.Size(m)
}
func (m *BroadcastStateEventResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastStateEventResp.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastStateEventResp proto.InternalMessageInfo

func (m *BroadcastStateEventResp) GetRespId() int64 {
	if m != nil {
		return m.RespId
	}
	return 0
}

func (m *BroadcastStateEventResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BroadcastStateEventResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 踢出连接
type KickOutReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	ConnectionId         string   `protobuf:"bytes,3,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickOutReq) Reset()         { *m = KickOutReq{} }
func (m *KickOutReq) String() string { return proto.CompactTextString(m) }
func (*KickOutReq) ProtoMessage()    {}
func (*KickOutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{30}
}

func (m *KickOutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickOutReq.Unmarshal(m, b)
}
func (m *KickOutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickOutReq.Marshal(b, m, deterministic)
}
func (m *KickOutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickOutReq.Merge(m, src)
}
func (m *KickOutReq) XXX_Size() int {
	return xxx_messageInfo_KickOutReq.Size(m)
}
func (m *KickOutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KickOutReq.DiscardUnknown(m)
}

var xxx_messageInfo_KickOutReq proto.InternalMessageInfo

func (m *KickOutReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *KickOutReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *KickOutReq) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

type ClientSendGiftReq struct {
	ReceiverId           []int32  `protobuf:"varint,1,rep,packed,name=receiverId,proto3" json:"receiverId,omitempty"`
	MetaGiftId           string   `protobuf:"bytes,2,opt,name=metaGiftId,proto3" json:"metaGiftId,omitempty"`
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientSendGiftReq) Reset()         { *m = ClientSendGiftReq{} }
func (m *ClientSendGiftReq) String() string { return proto.CompactTextString(m) }
func (*ClientSendGiftReq) ProtoMessage()    {}
func (*ClientSendGiftReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{31}
}

func (m *ClientSendGiftReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSendGiftReq.Unmarshal(m, b)
}
func (m *ClientSendGiftReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSendGiftReq.Marshal(b, m, deterministic)
}
func (m *ClientSendGiftReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSendGiftReq.Merge(m, src)
}
func (m *ClientSendGiftReq) XXX_Size() int {
	return xxx_messageInfo_ClientSendGiftReq.Size(m)
}
func (m *ClientSendGiftReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSendGiftReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSendGiftReq proto.InternalMessageInfo

func (m *ClientSendGiftReq) GetReceiverId() []int32 {
	if m != nil {
		return m.ReceiverId
	}
	return nil
}

func (m *ClientSendGiftReq) GetMetaGiftId() string {
	if m != nil {
		return m.MetaGiftId
	}
	return ""
}

func (m *ClientSendGiftReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type ClientSendGiftResp struct {
	RespId               int64    `protobuf:"varint,101,opt,name=respId,proto3" json:"respId,omitempty"`
	Code                 int32    `protobuf:"varint,102,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,103,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientSendGiftResp) Reset()         { *m = ClientSendGiftResp{} }
func (m *ClientSendGiftResp) String() string { return proto.CompactTextString(m) }
func (*ClientSendGiftResp) ProtoMessage()    {}
func (*ClientSendGiftResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{32}
}

func (m *ClientSendGiftResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSendGiftResp.Unmarshal(m, b)
}
func (m *ClientSendGiftResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSendGiftResp.Marshal(b, m, deterministic)
}
func (m *ClientSendGiftResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSendGiftResp.Merge(m, src)
}
func (m *ClientSendGiftResp) XXX_Size() int {
	return xxx_messageInfo_ClientSendGiftResp.Size(m)
}
func (m *ClientSendGiftResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSendGiftResp.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSendGiftResp proto.InternalMessageInfo

func (m *ClientSendGiftResp) GetRespId() int64 {
	if m != nil {
		return m.RespId
	}
	return 0
}

func (m *ClientSendGiftResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ClientSendGiftResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BroadcastSendGiftReq struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ReqId                int64    `protobuf:"varint,101,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastSendGiftReq) Reset()         { *m = BroadcastSendGiftReq{} }
func (m *BroadcastSendGiftReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastSendGiftReq) ProtoMessage()    {}
func (*BroadcastSendGiftReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5696bb5d84478598, []int{33}
}

func (m *BroadcastSendGiftReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastSendGiftReq.Unmarshal(m, b)
}
func (m *BroadcastSendGiftReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastSendGiftReq.Marshal(b, m, deterministic)
}
func (m *BroadcastSendGiftReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastSendGiftReq.Merge(m, src)
}
func (m *BroadcastSendGiftReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastSendGiftReq.Size(m)
}
func (m *BroadcastSendGiftReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastSendGiftReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastSendGiftReq proto.InternalMessageInfo

func (m *BroadcastSendGiftReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *BroadcastSendGiftReq) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func init() {
	proto.RegisterEnum("MetaGateway.CmdId", CmdId_name, CmdId_value)
	proto.RegisterType((*Nil)(nil), "MetaGateway.Nil")
	proto.RegisterType((*BaseReq)(nil), "MetaGateway.BaseReq")
	proto.RegisterType((*BaseResp)(nil), "MetaGateway.BaseResp")
	proto.RegisterType((*Ping)(nil), "MetaGateway.Ping")
	proto.RegisterType((*Pong)(nil), "MetaGateway.Pong")
	proto.RegisterType((*LoginReq)(nil), "MetaGateway.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "MetaGateway.LoginResp")
	proto.RegisterType((*LoginAck)(nil), "MetaGateway.LoginAck")
	proto.RegisterType((*LogoutReq)(nil), "MetaGateway.LogoutReq")
	proto.RegisterType((*LogoutResp)(nil), "MetaGateway.LogoutResp")
	proto.RegisterType((*SendMessageReq)(nil), "MetaGateway.SendMessageReq")
	proto.RegisterType((*SendMessageResp)(nil), "MetaGateway.SendMessageResp")
	proto.RegisterType((*Message)(nil), "MetaGateway.Message")
	proto.RegisterType((*SyncMessageReq)(nil), "MetaGateway.SyncMessageReq")
	proto.RegisterType((*SyncMessageResp)(nil), "MetaGateway.SyncMessageResp")
	proto.RegisterType((*SyncHistoryMessageReq)(nil), "MetaGateway.SyncHistoryMessageReq")
	proto.RegisterType((*SyncHistoryMessageResp)(nil), "MetaGateway.SyncHistoryMessageResp")
	proto.RegisterType((*SyncMessageNotifyReq)(nil), "MetaGateway.SyncMessageNotifyReq")
	proto.RegisterType((*UserStateEvent)(nil), "MetaGateway.UserStateEvent")
	proto.RegisterType((*SceneChangeReq)(nil), "MetaGateway.SceneChangeReq")
	proto.RegisterType((*PassThroughUser)(nil), "MetaGateway.PassThroughUser")
	proto.RegisterType((*PassThroughLevel)(nil), "MetaGateway.PassThroughLevel")
	proto.RegisterMapType((map[string]*PassThroughLevelFifth)(nil), "MetaGateway.PassThroughLevel.FifthEntry")
	proto.RegisterType((*PassThroughLevelFifth)(nil), "MetaGateway.PassThroughLevelFifth")
	proto.RegisterType((*ClientPassThroughEventReq)(nil), "MetaGateway.ClientPassThroughEventReq")
	proto.RegisterType((*BroadcastPassThroughEventReq)(nil), "MetaGateway.BroadcastPassThroughEventReq")
	proto.RegisterMapType((map[int32]*PassThroughLevel)(nil), "MetaGateway.BroadcastPassThroughEventReq.LevelEntry")
	proto.RegisterType((*Box)(nil), "MetaGateway.Box")
	proto.RegisterMapType((map[int32]int32)(nil), "MetaGateway.Box.SeatEntry")
	proto.RegisterType((*ClientStateEventReq)(nil), "MetaGateway.ClientStateEventReq")
	proto.RegisterType((*ClientStateEventResp)(nil), "MetaGateway.ClientStateEventResp")
	proto.RegisterType((*BroadcastStateEventReq)(nil), "MetaGateway.BroadcastStateEventReq")
	proto.RegisterMapType((map[string]*Box)(nil), "MetaGateway.BroadcastStateEventReq.BoxEntry")
	proto.RegisterType((*BroadcastStateEventResp)(nil), "MetaGateway.BroadcastStateEventResp")
	proto.RegisterType((*KickOutReq)(nil), "MetaGateway.KickOutReq")
	proto.RegisterType((*ClientSendGiftReq)(nil), "MetaGateway.ClientSendGiftReq")
	proto.RegisterType((*ClientSendGiftResp)(nil), "MetaGateway.ClientSendGiftResp")
	proto.RegisterType((*BroadcastSendGiftReq)(nil), "MetaGateway.BroadcastSendGiftReq")
}

func init() { proto.RegisterFile("MetaGateway.proto", fileDescriptor_5696bb5d84478598) }

var fileDescriptor_5696bb5d84478598 = []byte{
	// 1608 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4b, 0x6f, 0xdb, 0xc6,
	0x16, 0x0e, 0x5f, 0xb6, 0x74, 0xe4, 0xe7, 0xd8, 0x91, 0x79, 0x65, 0xc7, 0x96, 0x99, 0xdc, 0x40,
	0xf7, 0xe2, 0x5e, 0xb5, 0x70, 0x8a, 0x34, 0xe8, 0xc2, 0x40, 0x1c, 0xe4, 0xe1, 0xbc, 0xea, 0xd2,
	0x49, 0x0b, 0x04, 0x06, 0x0a, 0x9a, 0x1c, 0xc9, 0x84, 0x25, 0x52, 0xe6, 0x50, 0x8a, 0x95, 0x3f,
	0xd0, 0xa2, 0x9b, 0x2c, 0x1b, 0xa0, 0x40, 0xff, 0x43, 0x77, 0xdd, 0x75, 0x5f, 0xf4, 0x27, 0x75,
	0x51, 0xcc, 0x0c, 0x29, 0xce, 0x48, 0xa4, 0xab, 0x14, 0xda, 0xf1, 0x3c, 0x66, 0xce, 0x37, 0xe7,
	0x7c, 0x73, 0x66, 0x86, 0xb0, 0xfa, 0x02, 0xc7, 0xce, 0x63, 0x27, 0xc6, 0x6f, 0x9d, 0x61, 0xb3,
	0x17, 0x85, 0x71, 0x88, 0x2a, 0x82, 0xca, 0x32, 0x40, 0x7b, 0xe9, 0x77, 0xac, 0x1d, 0x98, 0x3f,
	0x70, 0x08, 0xb6, 0xf1, 0x05, 0x5a, 0x07, 0x23, 0xc2, 0x17, 0x87, 0x9e, 0x89, 0xeb, 0x4a, 0x43,
	0xb3, 0xb9, 0x60, 0x1d, 0x41, 0x89, 0x3b, 0x90, 0x1e, 0xaa, 0xc2, 0x5c, 0x84, 0x49, 0x6f, 0xe4,
	0x92, 0x48, 0x08, 0x81, 0xee, 0x86, 0x1e, 0x36, 0x5b, 0x75, 0xa5, 0x61, 0xd8, 0xec, 0x1b, 0x99,
	0x30, 0xdf, 0xc5, 0x84, 0x38, 0x6d, 0x6c, 0xb6, 0xeb, 0x4a, 0xa3, 0x6c, 0xa7, 0xa2, 0xb5, 0x05,
	0xfa, 0x91, 0x1f, 0xb4, 0x0b, 0xe2, 0x9d, 0x80, 0x7e, 0x14, 0x06, 0x6d, 0xb4, 0x04, 0x6a, 0x4c,
	0x4c, 0x85, 0x99, 0xd4, 0x98, 0xcc, 0x28, 0xf6, 0x07, 0x05, 0x4a, 0xcf, 0xc3, 0xb6, 0x1f, 0xd0,
	0x05, 0x57, 0x61, 0xae, 0x4f, 0x70, 0x74, 0xe8, 0xb1, 0x30, 0x86, 0x9d, 0x48, 0x14, 0x58, 0x1c,
	0x9e, 0xe3, 0xc0, 0x54, 0xd9, 0x60, 0x2e, 0x50, 0x6f, 0x07, 0x93, 0x67, 0x78, 0x68, 0x6a, 0x75,
	0xa5, 0xb1, 0x60, 0x27, 0x12, 0x05, 0x10, 0x0f, 0x7b, 0xd8, 0xd4, 0x39, 0x00, 0xfa, 0x8d, 0xb6,
	0xa0, 0xdc, 0xa1, 0x51, 0x5e, 0x51, 0x83, 0xc1, 0x0c, 0x99, 0xa2, 0x60, 0xe1, 0x5f, 0x41, 0x39,
	0x41, 0x36, 0xb3, 0x4c, 0xef, 0x27, 0x8b, 0xbd, 0xef, 0x9e, 0xff, 0x23, 0x48, 0xbb, 0x0c, 0x52,
	0xd8, 0x8f, 0x8b, 0xe9, 0x61, 0x03, 0xa4, 0x2e, 0x33, 0x83, 0xfd, 0xab, 0x02, 0x4b, 0xc7, 0x38,
	0xf0, 0x5e, 0x70, 0x99, 0x06, 0xaf, 0x43, 0x25, 0xb1, 0x32, 0xfc, 0xbc, 0x5e, 0xa2, 0x8a, 0x7a,
	0xb8, 0x1d, 0x1f, 0x07, 0xf1, 0x0b, 0xd2, 0x3e, 0xf4, 0x58, 0x35, 0xca, 0xb6, 0xa8, 0xa2, 0x01,
	0xdd, 0x30, 0x88, 0x71, 0x10, 0x9b, 0x73, 0x3c, 0x60, 0x22, 0x52, 0xd8, 0x6e, 0x18, 0x0c, 0x0e,
	0x3d, 0x73, 0x9e, 0x19, 0x12, 0x09, 0xd5, 0xa0, 0x44, 0xbf, 0x58, 0xc8, 0x12, 0x0b, 0x39, 0x92,
	0x0b, 0xd2, 0xf1, 0x93, 0x02, 0xcb, 0x12, 0x74, 0xd2, 0xa3, 0xc8, 0x08, 0x8e, 0x06, 0x38, 0xe2,
	0xc8, 0x14, 0x8e, 0x4c, 0x50, 0x4d, 0x81, 0x7d, 0x36, 0x89, 0x7d, 0xaf, 0xc2, 0x7c, 0x82, 0x4c,
	0x58, 0xb3, 0x52, 0xb8, 0x66, 0x75, 0x6c, 0xcd, 0x74, 0x4c, 0x3f, 0x22, 0x61, 0xc4, 0xb6, 0x80,
	0x66, 0x27, 0xd2, 0x78, 0x75, 0xf4, 0xc9, 0xea, 0xd4, 0xa0, 0x44, 0x70, 0xe0, 0xb1, 0xcd, 0xc6,
	0xc9, 0x37, 0x92, 0xc7, 0x57, 0x3f, 0x3f, 0xb9, 0xfa, 0xb1, 0x0c, 0x96, 0x26, 0x33, 0x28, 0xd4,
	0xb6, 0x2c, 0xd7, 0x76, 0x0b, 0xca, 0x6e, 0x84, 0x9d, 0x18, 0x7b, 0xf7, 0x63, 0x13, 0x18, 0xec,
	0x4c, 0x61, 0xbd, 0x81, 0xa5, 0xe3, 0x61, 0xe0, 0x0a, 0x4c, 0x9b, 0x6e, 0xfd, 0xba, 0xb4, 0xfe,
	0x7c, 0x2e, 0xfc, 0x42, 0xb9, 0x20, 0x4e, 0x4e, 0x7a, 0xa8, 0x01, 0x7a, 0x97, 0xb4, 0x69, 0x5f,
	0xd3, 0x1a, 0x95, 0xbd, 0xf5, 0xa6, 0xd8, 0xa4, 0x53, 0x3f, 0xe6, 0x41, 0x2b, 0xdb, 0x0d, 0xa3,
	0x14, 0x03, 0xfb, 0x96, 0xb0, 0x69, 0x93, 0xd8, 0x66, 0xc0, 0x90, 0x1f, 0x15, 0xb8, 0x4e, 0x31,
	0x3f, 0xf1, 0x49, 0x1c, 0x46, 0x43, 0x21, 0x2f, 0x59, 0xb3, 0xd4, 0xa4, 0x66, 0x99, 0xf1, 0x48,
	0x97, 0x78, 0x94, 0xe5, 0xca, 0xb8, 0x8a, 0x2b, 0x73, 0x75, 0x6d, 0x9c, 0x2b, 0xf9, 0xd9, 0xfc,
	0x5e, 0x81, 0x6a, 0x1e, 0xb2, 0x8f, 0x4a, 0xea, 0x6c, 0x92, 0xd4, 0x81, 0x75, 0xa1, 0xae, 0x2f,
	0xc3, 0xd8, 0x6f, 0x0d, 0xc7, 0xa9, 0xa3, 0x8c, 0x95, 0xc7, 0x82, 0x85, 0xd8, 0x89, 0xda, 0x38,
	0x7e, 0xcd, 0x93, 0xa8, 0xb2, 0x75, 0x4b, 0xba, 0x82, 0x85, 0xff, 0xa1, 0xc0, 0x12, 0x75, 0x38,
	0x8e, 0x9d, 0x18, 0x3f, 0x1c, 0x50, 0x4e, 0x2f, 0x80, 0x72, 0xc9, 0x22, 0xa8, 0xb6, 0x72, 0x49,
	0xa5, 0x21, 0xa3, 0x89, 0x6a, 0x2b, 0x43, 0x2a, 0xbd, 0x63, 0x25, 0x52, 0x6d, 0xe5, 0x1d, 0x65,
	0xbf, 0xe7, 0x47, 0xd8, 0x8d, 0xfd, 0x30, 0x30, 0xf5, 0xba, 0xd6, 0x50, 0xed, 0x4c, 0x41, 0x41,
	0x85, 0x41, 0xc7, 0x0f, 0x30, 0x9d, 0xbb, 0x4f, 0xd8, 0xd6, 0x33, 0x6c, 0x49, 0x27, 0xd4, 0xbd,
	0x24, 0xd5, 0xdd, 0x82, 0x05, 0x87, 0xcd, 0x92, 0x8c, 0x05, 0x96, 0x23, 0x49, 0x47, 0xd3, 0xda,
	0x8a, 0xc2, 0xae, 0x59, 0xe1, 0x69, 0xa5, 0xdf, 0xd6, 0x0f, 0xb4, 0xb9, 0xbb, 0x38, 0xc0, 0x0f,
	0xce, 0x9c, 0x80, 0x53, 0x6b, 0x0b, 0xca, 0x84, 0x6a, 0x84, 0xc4, 0x65, 0x0a, 0x5a, 0x07, 0x26,
	0xb0, 0xa4, 0xb1, 0x3a, 0x24, 0x22, 0x9d, 0x1e, 0x5f, 0xfa, 0xbc, 0x9b, 0x1b, 0x36, 0xfb, 0x16,
	0xe0, 0xea, 0xe3, 0x67, 0x7a, 0x4e, 0x6e, 0xbf, 0x86, 0xe5, 0x23, 0x87, 0x90, 0x57, 0x67, 0x51,
	0xd8, 0x6f, 0x9f, 0xd1, 0x2c, 0xa3, 0x4f, 0x40, 0xa7, 0x43, 0x18, 0x8e, 0xca, 0xde, 0xa6, 0x44,
	0x26, 0xb9, 0x0c, 0x36, 0x73, 0xa4, 0x28, 0x7a, 0x0e, 0x21, 0xe9, 0x46, 0xa5, 0xdf, 0xd6, 0xef,
	0x0a, 0xac, 0x08, 0x13, 0x3f, 0xc7, 0x03, 0xdc, 0xa1, 0x0b, 0xe9, 0xd0, 0x8f, 0xd1, 0x7d, 0x23,
	0x15, 0xd1, 0x3e, 0x18, 0x2d, 0xbf, 0x15, 0x9f, 0x99, 0x1a, 0x63, 0x70, 0x43, 0x0a, 0x3a, 0x3e,
	0x4f, 0xf3, 0x11, 0x75, 0x7d, 0x18, 0xc4, 0xd1, 0xd0, 0xe6, 0xc3, 0x6a, 0x27, 0x00, 0x99, 0x12,
	0xad, 0x80, 0x76, 0x8e, 0x87, 0x49, 0x5b, 0xa7, 0x9f, 0xe8, 0x1e, 0x18, 0x03, 0xa7, 0xd3, 0xe7,
	0xcd, 0xa4, 0xb2, 0x67, 0x5d, 0x39, 0x3f, 0x9b, 0xc9, 0xe6, 0x03, 0xbe, 0x50, 0xef, 0x29, 0x96,
	0x0f, 0xd7, 0x73, 0x7d, 0xe8, 0x15, 0xcd, 0x4f, 0x8f, 0x0f, 0xd5, 0xf7, 0x38, 0x2d, 0x55, 0x89,
	0x96, 0x9a, 0x44, 0x4b, 0x3d, 0xa5, 0x65, 0x15, 0xe6, 0x7c, 0x62, 0x63, 0xa7, 0x93, 0x1c, 0x06,
	0x89, 0x64, 0xb9, 0xf0, 0xaf, 0x07, 0xac, 0xef, 0x0b, 0x01, 0x79, 0xae, 0xf1, 0x05, 0xfa, 0x54,
	0xaa, 0xcc, 0x56, 0xd1, 0x22, 0x68, 0x91, 0x92, 0xd2, 0xe4, 0x17, 0xfd, 0x3b, 0x0d, 0xb6, 0x0e,
	0xa2, 0xd0, 0xf1, 0x5c, 0x87, 0xe4, 0x06, 0x7a, 0x0a, 0x06, 0xab, 0x4c, 0xd2, 0x50, 0x3e, 0x93,
	0x22, 0x5d, 0x35, 0xb2, 0xc9, 0x92, 0x93, 0x94, 0x86, 0x4d, 0x31, 0x02, 0xad, 0xb2, 0xa9, 0xa6,
	0x01, 0x7d, 0x17, 0xaa, 0x6d, 0xa7, 0x8b, 0x0f, 0x30, 0xbd, 0x9b, 0xf9, 0x5d, 0x6c, 0xe3, 0xae,
	0xe3, 0x07, 0x7e, 0xd0, 0x4e, 0x1a, 0x69, 0x81, 0x95, 0xee, 0x22, 0x6a, 0x61, 0xfc, 0x4c, 0xb6,
	0x44, 0xa6, 0x40, 0xb7, 0x60, 0x51, 0xec, 0x35, 0x74, 0xbf, 0xd2, 0x06, 0x24, 0x2b, 0xf3, 0x13,
	0x56, 0xfb, 0x06, 0x20, 0x5b, 0x98, 0x48, 0x2f, 0x83, 0xd3, 0xeb, 0x8e, 0x4c, 0xaf, 0x1b, 0x57,
	0xd2, 0x4b, 0x64, 0xd6, 0xcf, 0x0a, 0x68, 0x07, 0xe1, 0xe5, 0x04, 0x91, 0xb6, 0x01, 0x48, 0xff,
	0x94, 0xf4, 0x1c, 0x37, 0xdb, 0xf5, 0x82, 0x06, 0x35, 0x41, 0x27, 0xd8, 0x89, 0x59, 0x43, 0xab,
	0xec, 0xd5, 0xe4, 0xfa, 0x84, 0x97, 0xcd, 0x63, 0xec, 0xc4, 0xbc, 0x0a, 0xcc, 0xaf, 0xf6, 0x39,
	0x94, 0x47, 0xaa, 0x1c, 0xfc, 0xeb, 0x22, 0x7e, 0x43, 0x04, 0x78, 0x02, 0x6b, 0x9c, 0x8f, 0xc2,
	0xae, 0xc7, 0x17, 0x1f, 0xdf, 0x23, 0x8a, 0x9e, 0x3a, 0xeb, 0x93, 0xb3, 0xcf, 0xec, 0x16, 0xfd,
	0x5e, 0x85, 0xea, 0x88, 0xac, 0x45, 0xf8, 0xb5, 0xe9, 0xf0, 0xef, 0x83, 0x76, 0x1a, 0x5e, 0x26,
	0x24, 0xfe, 0x5f, 0xfe, 0x7e, 0x90, 0x42, 0xd0, 0x32, 0xf0, 0x0a, 0xd0, 0x81, 0x93, 0xec, 0xd3,
	0xa7, 0x67, 0xdf, 0x13, 0x28, 0xa5, 0x93, 0xe5, 0xb4, 0xb6, 0xdb, 0x32, 0xf7, 0x56, 0xc6, 0xb9,
	0x20, 0x56, 0xf3, 0x5b, 0xd8, 0xc8, 0x45, 0x3b, 0xb3, 0x94, 0x9f, 0x00, 0x3c, 0xf3, 0xdd, 0xf3,
	0x2f, 0xf9, 0x83, 0xa9, 0xe8, 0x79, 0x99, 0x3e, 0x18, 0x55, 0xe1, 0xc1, 0x68, 0xc1, 0x82, 0x1b,
	0x06, 0x01, 0x3f, 0x97, 0x93, 0x3b, 0x56, 0xd9, 0x96, 0x74, 0x96, 0x0f, 0xab, 0x09, 0x5d, 0x70,
	0xe0, 0x3d, 0xf6, 0x5b, 0x2c, 0xc8, 0x36, 0x40, 0x84, 0x5d, 0xec, 0x0f, 0x92, 0x40, 0x34, 0xad,
	0x82, 0x86, 0xda, 0xbb, 0x34, 0x23, 0x7e, 0x2b, 0xce, 0xb6, 0x52, 0xa6, 0x29, 0x60, 0xe6, 0x1b,
	0x40, 0xe3, 0xa1, 0x66, 0x96, 0xa4, 0x47, 0xb0, 0x9e, 0x55, 0x41, 0x58, 0x89, 0x70, 0x85, 0x57,
	0xe4, 0x2b, 0x7c, 0x2e, 0xc6, 0xff, 0xfe, 0x69, 0x80, 0xf1, 0xa0, 0xeb, 0x1d, 0x7a, 0xa8, 0x02,
	0xf3, 0xaf, 0x83, 0x67, 0x41, 0xf8, 0x36, 0x58, 0xb9, 0x86, 0x16, 0xa1, 0x7c, 0xe4, 0x07, 0x6d,
	0x66, 0x59, 0x51, 0x98, 0x18, 0xa6, 0xa2, 0x8a, 0x56, 0x61, 0x31, 0x7d, 0xfe, 0x73, 0x55, 0x05,
	0x21, 0x58, 0x1a, 0xbd, 0xbb, 0xb9, 0x6e, 0x61, 0xe4, 0x76, 0xdf, 0x3d, 0xe7, 0xaa, 0xc5, 0xc4,
	0x8d, 0xbf, 0x85, 0xb9, 0x6e, 0x19, 0xad, 0xc1, 0x72, 0xf6, 0xf8, 0xe5, 0xca, 0x15, 0xb4, 0x05,
	0x66, 0x4e, 0xcf, 0xe0, 0xd6, 0xeb, 0xe8, 0x46, 0x7a, 0xc2, 0xc9, 0x04, 0xe4, 0xe6, 0x2a, 0xaa,
	0x41, 0x75, 0xa2, 0xc6, 0xdc, 0xb6, 0x81, 0x36, 0x61, 0x63, 0xb2, 0x28, 0xdc, 0x68, 0xa2, 0x0d,
	0x58, 0x93, 0x9f, 0xcc, 0xdc, 0xb0, 0x83, 0x4c, 0x58, 0x1f, 0x7b, 0x90, 0x72, 0x4b, 0x9d, 0x0d,
	0x91, 0xde, 0x3e, 0xdc, 0xb0, 0xcb, 0x86, 0xc8, 0xef, 0x16, 0x6e, 0xb1, 0xd0, 0x36, 0xd4, 0x72,
	0x5f, 0x07, 0xdc, 0x7e, 0x13, 0xed, 0xc0, 0x66, 0xfe, 0x1d, 0x9d, 0x3b, 0xdc, 0x42, 0x16, 0x6c,
	0x17, 0x1e, 0xf0, 0xdc, 0xe7, 0xff, 0xe8, 0x26, 0xec, 0x14, 0xf9, 0xa4, 0x13, 0x35, 0x69, 0xa4,
	0xfc, 0xce, 0xc3, 0x1d, 0x30, 0xaa, 0x0b, 0x87, 0x7c, 0x5e, 0xae, 0x5b, 0x6c, 0xfd, 0xd2, 0x45,
	0x94, 0x1b, 0xda, 0x6c, 0xfd, 0xa2, 0x21, 0x1d, 0x72, 0x46, 0xab, 0x97, 0xc7, 0x5d, 0x6e, 0xf6,
	0xd1, 0xbf, 0x61, 0xf7, 0xaa, 0xeb, 0x01, 0x77, 0xeb, 0xa2, 0xdb, 0x60, 0x5d, 0xe1, 0x96, 0x46,
	0x0b, 0xd0, 0x26, 0x7f, 0xf1, 0x48, 0xef, 0x0c, 0x6e, 0xfb, 0x4d, 0xd9, 0xfb, 0xa0, 0x01, 0x12,
	0x7a, 0xdd, 0x31, 0x8e, 0x06, 0xbe, 0x8b, 0xd1, 0x5d, 0x98, 0x4f, 0x5a, 0x10, 0xda, 0x90, 0x7a,
	0x61, 0xd6, 0x98, 0x6a, 0x72, 0x93, 0x7c, 0xe9, 0x77, 0xac, 0x6b, 0xe8, 0x29, 0xac, 0x4e, 0xc4,
	0x42, 0xbb, 0x92, 0x63, 0xde, 0x9b, 0x27, 0x77, 0xae, 0x7d, 0xa8, 0x08, 0xf9, 0x43, 0xf2, 0xf9,
	0x22, 0xa7, 0x3c, 0x77, 0xfc, 0x29, 0xac, 0xe5, 0x94, 0x0e, 0xdd, 0x9c, 0xe2, 0xdc, 0xa9, 0xdd,
	0xfa, 0x7b, 0x27, 0xd2, 0xb3, 0xae, 0xa1, 0x37, 0x42, 0x25, 0xc7, 0x6b, 0x80, 0xfe, 0x33, 0xf5,
	0x8d, 0x2f, 0x0f, 0xff, 0xe9, 0x1c, 0xfb, 0xdd, 0x7a, 0xe7, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x39, 0x62, 0x52, 0x4b, 0x83, 0x15, 0x00, 0x00,
}
